name = "sanastot"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-20"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
